### ISSUE TITLE
Bug when using the command and its API

### ISSUE THREAD

**Issue by Nexus9w9** [Muqsit/CustomSizedInvMenu#1]
I'm having problems using this plugin or using the API of this plugin, when I try to use the /cinvmenu command the first time I get the window ok, but when I close and try again nothing appears, when I create a window using the API, when I execute the command that triggers its creation, I don't get anything, and I have a buggy inventory.

**Comment by Muqsit** [comment]
Are you running the plugin from .phar?

**Comment by Nexus9w9** [comment]
> Are you running the plugin from .phar?

Yes, I tried using .phar and extracting the 3 files in my plugins directory. (Note: I removed the onEnable and CommandSender methods.)

**Comment by Nexus9w9** [comment]
Uploading 2023-07-26 00-25-43.mp4…

> Are you running the plugin from .phar?

Yes, I tried using .phar and extracting the 3 files in my plugins directory. (Note: I removed the onEnable and CommandSender methods.)

**Comment by Nexus9w9** [comment]
My problem is solved with the new update, thanks
